/**
 * Created by Eric Stansbury on 6/7/2019.
 */

public class RepTriggerHandler {
    //public static void handleAfterDelete(List<Rep__c> reps){
        //Set<Id> repIds = new Map<Id,Rep__c>(reps).keySet();
        //List<String> groupNames = new List<String>();
        //for (Id repId : repIds){
            //groupNames.add('Rep-' + repId);
        //}

        //delete [select id from Group where Name in :groupNames];
    //}
}